links:
 checkv_link: https://portal.nersc.gov/CheckV/checkv-db-v1.5.tar.gz
 dbcan_link: https://zenodo.org/records/18622157/files/dbcan_db_v5.1.2.tar.gz
directories:
  input_dir: /path/to/input_dir
  output_dir: /path/to/output_dir
  bakta_db: /path/to/bakta_6.0/db
  blast_db: /path/to/NCBI_core_nt
  eggnog_db: /path/to/eggnog
  gtdbtk_db: /path/to/GTDB/release226
  platon_db: /path/to/platon/db
resources:
  threads: 24
parameters:
  nt_version: core_nt
  medaka_model: r1041_e82_400bps_sup_v4.3.0
  genus: